### ISSUE TITLE
bug反馈，使用太极环境

### ISSUE THREAD

**Issue by enterdawn** [qssq/feedback#42]
如果您看到了本文本,且您的Q++不能在QQ->设置中找到Q++,请根据时间排序把最新得文件分享给作者。作者联系方式:
QQ: 35068264(可能被封) 邮箱:qssq521@gmail.com qssq666@foxmail.com
App版本:8.1.0_1232
插件版本:1.3.4_48
系统包名:com.tencent.mobileqq
应用包名:com.tencent.mobileqq
应用进程:com.tencent.mobileqq
品牌:Xiaomi
型号:Redmi K20 Pro
安卓版本:28
CPUABI:[arm64-v8a, armeabi-v7a, armeabi]
是否Root(经供参考):false
退出原因:无法兼容此版本QQ
如果您的加密库1，2已经成功安装,请无视现在看到的错误,不要再反馈给作者了,作者不想再解释N遍,这也是我懒得回答的原因。
崩溃原因:java.lang.NoSuchMethodError: aioc(com.tencent.mobileqq.app.QQAppInterface)#exact
at de.robv.android.xposed.XposedHelpers.findConstructorExact(SourceFile:614)
at de.robv.android.xposed.XposedHelpers.findAndHookConstructor(SourceFile:627)
at de.robv.android.xposed.XposedHelpers.findAndHookConstructor(SourceFile:637)
at android.support.v4.app.fi.ooooooo(ProguardQPLUSPLUS:1242)
at android.support.v4.app.fi.ooooo(ProguardQPLUSPLUS:770)
at android.support.v4.app.by.ooooo(ProguardQPLUSPLUS:224)
at android.support.v4.app.by.ooooo(ProguardQPLUSPLUS:50)
at android.support.v4.app.by$3.afterHookedMethod(ProguardQPLUSPLUS:154)
at de.robv.android.xposed.DexposedBridge.handleHookedArtMethod(SourceFile:275)
at de.robv.android.xposed.DexposedBridge.handleHookedArtMethod(SourceFile:205)
at android.app.Instrumentation_1874524616.callApplicationOnCreate(Unknown Source:18)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6021)
at android.app.ActivityThread.access$1200(ActivityThread.java:206)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1686)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:201)
at android.app.ActivityThread.main(ActivityThread.java:6882)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by qssq** [comment]
更新q++ 推荐傀儡术
