### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by lvg3618** [qssq/feedback#52]
如果您看到了本文本,且您的Q++不能在QQ->设置中找到Q++,请根据时间排序把最新得文件分享给作者。作者联系方式:
QQ: 35068264(可能被封) 邮箱:qssq521@gmail.com qssq666@foxmail.com
App版本:8.1.3_1246
插件版本:1.3.5_49
系统包名:com.tencent.mobileqq
应用包名:com.tencent.mobileqq
应用进程:com.tencent.mobileqq
品牌:xiaomi
型号:MI 5X
安卓版本:27
CPUABI:[arm64-v8a, armeabi-v7a, armeabi]
是否Root(经供参考):true
【已root用户无法安装模块请尝试切换工具->主动安装】
退出原因:无法兼容此版本QQ
如果您的加密库1，2已经成功安装,请无视现在看到的错误,不要再反馈给作者了,作者不想再解释N遍,这也是我懒得回答的原因。
崩溃原因:java.lang.NoSuchMethodError: aioc(com.tencent.mobileqq.app.QQAppInterface)#exact
	at de.robv.android.xposed.XposedHelpers.findConstructorExact(XposedHelpers.java:608)
	at de.robv.android.xposed.XposedHelpers.findAndHookConstructor(XposedHelpers.java:621)
	at de.robv.android.xposed.XposedHelpers.findAndHookConstructor(XposedHelpers.java:631)
	at android.support.v4.app.fi.ooooooo(ProguardQPLUSPLUS:1242)
	at android.support.v4.app.fi.ooooo(ProguardQPLUSPLUS:770)
	at android.support.v4.app.by.ooooo(ProguardQPLUSPLUS:224)
	at android.support.v4.app.by.ooooo(ProguardQPLUSPLUS:50)
	at android.support.v4.app.by$3.afterHookedMethod(ProguardQPLUSPLUS:154)
	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
	at EdHooker_.hook(Unknown Source:142)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5826)
	at com.elderdrivers.riru.edxp._hooker.yahfa.HandleBindAppHooker.hook(HandleBindAppHooker.java:21)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6651)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

**Comment by qssq** [comment]
降级qq
