### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by ddddddddddsa** [qssq/feedback#68]
如果您看到了本文本,且您的Q++不能在QQ->设置中找到Q++,请根据时间排序把最新得文件分享给作者。作者联系方式:
QQ: 35068264(可能被封) 邮箱:qssq521@gmail.com qssq521@gmail.com
App版本:8.8.0_1792
插件版本:1.3.8_53
系统包名:com.tencent.mobileqq
应用包名:com.tencent.mobileqq
应用进程:com.tencent.mobileqq
品牌:OnePlus
型号:GM1910
安卓版本:30
CPUABI:[arm64-v8a, armeabi-v7a, armeabi]
是否Root(经供参考):false
退出原因:无法找到包名:cn.qssq666.q.plus相关信息!
。
崩溃原因:android.content.pm.PackageManager$NameNotFoundException: hide.fail.add_qq 153016267
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:428)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:417)
	at java.lang.reflect.Method.invoke(Native Method)
	at exp.anf.invoke(Native Method)
	at exp.ano.ˏ(SourceFile:248)
	at exp.ane.invokeOriginalMethod(SourceFile:408)
	at exp.ane.a(SourceFile:246)
	at exp.ane.a(SourceFile:191)
	at android.app.ApplicationPackageManager_1881604088.getApplicationInfo(Unknown Source:29)
	at android.support.v4.app.em.getTryList(ProguardQPLUSPLUS:183)
	at cn.qssq666.EncryptUtilX.oooo000o(ProguardQPLUSPLUS:63)
	at cn.qssq666.EncryptUtilX.<clinit>(ProguardQPLUSPLUS:41)
	at cn.qssq666.EncryptUtilX.a7(Native Method)
	at android.support.v4.app.fh.ooooooo(ProguardQPLUSPLUS:76)
	at android.support.v4.app.fs$5.afterHookedMethod(ProguardQPLUSPLUS:556)
	at de.robv.android.xposed.ExposedHelper.afterHookedMethod(SourceFile:52)
	at exp.aps$ʼ.ᐝ(SourceFile:334)
	at exp.ane.a(SourceFile:262)
	at exp.ane.a(SourceFile:191)
	at com.tencent.mobileqq.activity.AboutActivity_23269984.doOnCreate(Unknown Source:18)
	at mqq.app.AppActivity.onCreate(P:107)
	at android.app.Activity.performCreate(Activity.java:8006)
	at android.app.Activity.performCreate(Activity.java:7990)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3584)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by qssq** [comment]
不再更新。
